// Generated from the Go doc tables (opDocs sorted by name, as builtinOps() does).

pub const KEYWORD_DOCS: &[(&str, &str)] = &[
    ("name", "Top-level: program name. `name \"myapp\"`"),
    ("about", "Top-level: program description. `about \"…\"`"),
    ("version", "Top-level: version. `version \"0.1.0\"`"),
    ("globals", "Top-level: open a block of `NAME = LITERAL` bindings shared by every command."),
    ("command", "Declare a callable command. Opens a block terminated by `end`."),
    ("catch", "Fallback for unknown command names. Body runs with the unknown name bound."),
    ("description", "Help text. Inside a `command` sets the command's; inside an `arg` block sets the arg's."),
    ("arg", "Declare a typed CLI argument. Inside: `type`, `default`, `description`, `optional`, `index`."),
    ("type", "Inside an arg block: `type string`/`int`/`float`/`bool`. Required."),
    ("default", "Inside an arg block: default literal; presence makes the arg optional."),
    ("optional", "Inside an arg block: arg may be omitted with no default."),
    ("index", "Inside an arg block: bind to a positional index (instead of a `-name` flag)."),
    ("private", "Hide command from CLI; only callable via `run`."),
    ("detached", "Don't wait on processes started by `shell_detached`."),
    ("proxy_args", "Skip arg parsing; argv → `${proxy_args}` for the body."),
    ("require_os", "Refuse to run on other OSes. Pass: `\"darwin\" \"linux\" \"windows\"`."),
    ("require_arch", "Refuse to run on other CPU architectures."),
    ("dir", "Set the cwd for the body."),
    ("on_signal", "Run HANDLER (another command) on SIGINT/SIGTERM."),
    ("env", "Set an env var for the body's `shell` calls."),
    ("do", "Open the executable body block."),
    ("end", "Close the most-recent block."),
];

pub const OP_DOCS: &[(&str, &str, &str)] = &[
    ("app_data_dir", "() → string", "Platform-aware app-data dir."),
    ("base64_decode", "(string) → string", "Base64-decode."),
    ("base64_encode", "(string) → string", "Base64-encode."),
    ("cache_dir", "() → string", "Platform-aware cache dir."),
    ("capitalize", "(string) → string", "Title-case first letter."),
    ("cd", "(string)", "Change the cwd of subsequent ops."),
    ("chmod", "(string, string)", "chmod path MODE (octal)."),
    ("contains", "(string, string) → bool", "Substring test."),
    ("cp", "(string, string)", "Copy src → dst."),
    ("crc32", "(string) → string", "CRC32 IEEE hex digest."),
    ("cwd", "() → string", "Current working directory."),
    ("dns_lookup", "(string) → []string", "Resolve host → IPs."),
    ("download", "(string, string)", "GET URL, save to DST."),
    ("eprintln", "(string)", "Print MSG + newline to stderr."),
    ("exists", "(string) → bool", "Return whether the path exists."),
    ("exit", "(int)", "Exit the process with the given code."),
    ("fail", "(string)", "Exit the command with the given message."),
    ("file_size", "(string) → int", "Return size in bytes."),
    ("format", "(string, any) → string", "fmt.Sprintf-style."),
    ("get_arch", "() → string", "amd64/arm64/…"),
    ("get_env", "(string) → string", "os.Getenv(name)."),
    ("get_os", "() → string", "darwin/linux/windows."),
    ("gzip", "(string, string)", "gzip SRC → DST."),
    ("has_prefix", "(string, string) → bool", "Prefix test."),
    ("has_suffix", "(string, string) → bool", "Suffix test."),
    ("hex_decode", "(string) → string", "Hex-decode."),
    ("hex_encode", "(string) → string", "Hex-encode."),
    ("home_dir", "() → string", "User home dir."),
    ("hostname", "() → string", "Host name."),
    ("http_delete", "(string) → string", "HTTP DELETE."),
    ("http_get", "(string) → string", "HTTP GET; return body as string."),
    ("http_post", "(string, string) → string", "HTTP POST; second arg is the body."),
    ("http_put", "(string, string) → string", "HTTP PUT."),
    ("if", "EXPR … end", "Run nested ops when EXPR holds. EXPR can be: `NAME == LIT` / `!= LIT` / `> N` / `< N` / `>= N` / `<= N` / bare `NAME` (truthy) / `not NAME` (falsy)."),
    ("if_call", "FUNC ARG … end", "Run nested ops if FUNC(ARG) is truthy. E.g. `if exists \"./bin\"`."),
    ("is_dir", "(string) → bool", "Return whether the path is a directory."),
    ("is_file", "(string) → bool", "Return whether the path is a regular file."),
    ("join", "([]any, string) → string", "Join with SEP."),
    ("json_get", "(any, string) → any", "Dotted-path lookup into a JSON value."),
    ("json_parse", "(string) → any", "Parse JSON to a value."),
    ("json_stringify", "(any) → string", "Marshal to JSON."),
    ("length", "(string) → int", "Length in bytes."),
    ("list_commands", "()", "Print the visible command list."),
    ("lower", "(string) → string", "Lowercase."),
    ("md5", "(string) → string", "MD5 hex digest."),
    ("md5_file", "(string) → string", "MD5 of the file at PATH."),
    ("mkdir", "(string)", "Create directories (with parents)."),
    ("mv", "(string, string)", "Rename src → dst."),
    ("now", "(string?) → string", "Current time. Formats: rfc3339, rfc822, unix, unix_milli, date, time, datetime, or any Go layout."),
    ("pid", "() → int", "Current process id."),
    ("port_check", "(string, string) → bool", "Can we open TCP to host:port?"),
    ("print", "(string)", "Print MSG + newline to stdout."),
    ("println", "(string)", "Alias for print."),
    ("read_file", "(string) → string", "Read PATH and return its contents."),
    ("regex_find_all", "(string, string) → []string", "Find all matches."),
    ("regex_match", "(string, string) → bool", "Test regex match."),
    ("regex_replace", "(string, string, string) → string", "Regex replace."),
    ("repeat", "(string, int) → string", "Repeat N times."),
    ("replace", "(string, string) → string", "Replace; second arg is \"OLD,NEW\"."),
    ("rm", "(string)", "Remove path (recursive)."),
    ("run", "(ident)", "Call another command."),
    ("set_env", "(string, string)", "os.Setenv(name, value)."),
    ("sha1", "(string) → string", "SHA1 hex digest."),
    ("sha1_file", "(string) → string", "SHA1 of the file at PATH."),
    ("sha256", "(string) → string", "SHA256 hex digest."),
    ("sha256_file", "(string) → string", "SHA256 of the file at PATH."),
    ("shell", "(string)", "Run CMD via bash (POSIX) or cmd.exe (Windows)."),
    ("shell_detached", "(string)", "Start CMD detached; return immediately."),
    ("shell_output", "(string) → string", "Run CMD; capture stdout as the return value."),
    ("sleep", "(number)", "Sleep for N seconds."),
    ("split", "(string, string) → []string", "Split by SEP."),
    ("tar_create", "(string, string)", "Gzipped-tar SRC_DIR → DST."),
    ("tar_extract", "(string, string)", "Extract SRC.tar.gz → DST dir."),
    ("temp_dir", "() → string", "OS temp dir."),
    ("touch", "(string)", "Touch a path."),
    ("trim", "(string) → string", "Strip surrounding whitespace."),
    ("ungzip", "(string, string)", "ungzip SRC → DST."),
    ("unix_to_iso", "(int) → string", "Unix seconds → RFC3339 UTC."),
    ("upper", "(string) → string", "Uppercase. Use via `X = upper \"hi\"`."),
    ("url_decode", "(string) → string", "URL-percent-decode."),
    ("url_encode", "(string) → string", "URL-percent-encode."),
    ("user", "() → string", "$USER."),
    ("write_file", "(string, string)", "Write CONTENT to PATH."),
    ("zip_create", "(string, string)", "Zip SRC_DIR → DST."),
    ("zip_extract", "(string, string)", "Extract SRC.zip → DST dir."),
];
