package opcatalog

// docFor returns signature and description for a built-in op.
func docFor(kind string) (signature, description string) {
	if d, ok := opDocs[kind]; ok {
		return d.signature, d.description
	}
	return "", "Built-in perch op."
}

type docEntry struct {
	signature   string
	description string
}

// opDocs is the human-readable catalog. Keep roughly in sync with docs/op-reference.md.
var opDocs = map[string]docEntry{
	"print":          {"(string)", "Print MSG + newline to stdout."},
	"println":        {"(string)", "Alias for print."},
	"eprintln":       {"(string)", "Print MSG + newline to stderr."},
	"shell":          {"(string)", "Run CMD via bash (POSIX) or cmd.exe (Windows). Deprecated — prefer exec."},
	"shell_output":   {"(string) → string", "Run CMD; capture stdout as the return value."},
	"shell_detached": {"(string)", "Start CMD detached; return immediately."},
	"shell_in":       {"(string, string)", "Run CMD with stdin data."},
	"try_shell":      {"(string)", "Run CMD; on failure bind err and continue (used inside try/rescue)."},
	"exec":           {"(word, word…)", "Run BIN directly (no shell). Each token is one argv slot. Requires declared bin."},
	"exec_chain":     {"(exec clauses…)", "Chain exec clauses with && / || / ; short-circuit semantics."},
	"pipe":           {"block → string", "Wire stdout→stdin between exec stages in-process."},
	"fail":           {"(string)", "Exit the command with the given message."},
	"exit":           {"(int)", "Exit the process with the given code."},
	"sleep":          {"(number)", "Sleep for N seconds."},
	"run":            {"(ident)", "Call another command in the same program."},
	"list_commands":  {"()", "Print the visible command list."},
	"export_ops_catalog": {"(string)", "Write a JSON catalog of all built-in ops to PATH."},

	"mkdir": {"(string)", "Create directories (with parents)."},
	"cp":    {"(string, string)", "Copy src → dst."},
	"mv":    {"(string, string)", "Rename or move src → dst."},
	"rm":    {"(string)", "Remove path (recursive)."},
	"cd":    {"(string)", "Change interpreter cwd for subsequent ops."},
	"chmod": {"(string, string)", "chmod path MODE (octal)."},
	"touch": {"(string)", "Create or update file timestamp."},
	"write_file":          {"(string, string)", "Write CONTENT to PATH."},
	"read_file":           {"(string) → string", "Read PATH and return contents."},
	"exists":              {"(string) → bool", "Return whether PATH exists."},
	"is_dir":              {"(string) → bool", "Return whether PATH is a directory."},
	"is_file":             {"(string) → bool", "Return whether PATH is a regular file."},
	"file_size":           {"(string) → int", "Return size in bytes."},
	"list_dir":            {"(string) → string", "List directory entries."},
	"glob":                {"(string) → string", "Glob pattern match."},
	"append_file":         {"(string, string)", "Append CONTENT to PATH."},
	"append_line":         {"(string, string)", "Append one line to PATH."},
	"ensure_dir":          {"(string)", "mkdir -p equivalent."},
	"make_executable":     {"(string)", "chmod +x on PATH."},
	"ensure_line_in_file": {"(string, string)", "Ensure LINE exists in PATH."},
	"replace_in_file":     {"(string, string, string)", "Replace OLD with NEW in PATH."},
	"backup_file":         {"(string)", "Copy PATH to PATH.bak."},
	"copy_dir":            {"(string, string)", "Recursively copy directory."},
	"symlink":             {"(string, string)", "Create symlink."},
	"read_link":           {"(string) → string", "Read symlink target."},
	"mktemp_dir":          {"() → string", "Create a temporary directory."},
	"mktemp_file":         {"() → string", "Create a temporary file."},

	"if":      {"EXPR … end", "Conditional block on comparison or truthiness."},
	"if_call": {"FUNC ARG … end", "Conditional when FUNC(ARG) is truthy."},
	"for_each": {"(list, ident) … end", "Iterate binding over list items."},
	"try":     {"block", "Try/rescue/finally error handling block."},
	"match":   {"EXPR … end", "Pattern dispatch block."},
	"os":      {"(string) … end", "Run body when host OS matches."},
	"arch":    {"(string) … end", "Run body when host arch matches."},

	"upper": {"(string) → string", "Uppercase a string."},
	"lower": {"(string) → string", "Lowercase a string."},
	"trim":  {"(string) → string", "Strip surrounding whitespace."},
	"capitalize": {"(string) → string", "Title-case first letter."},
	"length":     {"(string) → int", "Byte length of string."},
	"contains":   {"(string, string) → bool", "Substring test."},
	"has_prefix": {"(string, string) → bool", "Prefix test."},
	"has_suffix": {"(string, string) → bool", "Suffix test."},
	"replace":    {"(string, string) → string", "Replace; second arg is \"OLD,NEW\"."},
	"split":      {"(string, string) → []string", "Split by separator."},
	"join":       {"([]any, string) → string", "Join with separator."},
	"repeat":     {"(string, int) → string", "Repeat N times."},
	"format":     {"(string, any) → string", "fmt.Sprintf-style format."},

	"grep":        {"(string, string) → string", "Keep lines matching regex PAT."},
	"reject":      {"(string, string) → string", "Keep lines NOT matching PAT."},
	"cut":         {"(int, string) → string", "Nth whitespace field per line."},
	"head":        {"(int, string) → string", "First N lines."},
	"tail":        {"(int, string) → string", "Last N lines."},
	"sort_lines":  {"(string) → string", "Sort lines lexicographically."},
	"uniq_lines":  {"(string) → string", "Collapse adjacent duplicate lines."},
	"count_lines": {"(string) → int", "Count lines."},

	"md5": {"(string) → string", "MD5 hex digest of string."},
	"sha1": {"(string) → string", "SHA1 hex digest."},
	"sha256": {"(string) → string", "SHA256 hex digest."},
	"crc32": {"(string) → string", "CRC32 IEEE hex digest."},
	"md5_file":    {"(string) → string", "MD5 of file at PATH."},
	"sha1_file":   {"(string) → string", "SHA1 of file at PATH."},
	"sha256_file": {"(string) → string", "SHA256 of file at PATH."},
	"verify_sha256": {"(string, string) → bool", "Compare file hash to expected."},

	"base64_encode":  {"(string) → string", "Base64-encode."},
	"base64_decode":  {"(string) → string", "Base64-decode."},
	"hex_encode":     {"(string) → string", "Hex-encode."},
	"hex_decode":     {"(string) → string", "Hex-decode."},
	"url_encode":     {"(string) → string", "URL-percent-encode."},
	"url_decode":     {"(string) → string", "URL-percent-decode."},
	"json_parse":     {"(string) → any", "Parse JSON."},
	"json_stringify": {"(any) → string", "Marshal to JSON."},
	"json_get":       {"(any, string) → any", "Dotted-path lookup in JSON value."},

	"http_get":    {"(string) → string", "HTTP GET; return body."},
	"http_post":   {"(string, string) → string", "HTTP POST with body."},
	"http_put":    {"(string, string) → string", "HTTP PUT."},
	"http_delete": {"(string) → string", "HTTP DELETE."},
	"http_status": {"(string) → int", "HTTP status code only."},
	"download":    {"(string, string)", "GET URL, save to DST."},

	"gzip":        {"(string, string)", "gzip SRC → DST."},
	"ungzip":      {"(string, string)", "ungzip SRC → DST."},
	"tar_create":  {"(string, string)", "Gzipped tar SRC_DIR → DST."},
	"tar_extract": {"(string, string)", "Extract archive → DST."},
	"zip_create":  {"(string, string)", "Zip SRC_DIR → DST."},
	"zip_extract": {"(string, string)", "Extract zip → DST."},

	"now":         {"(string?) → string", "Current time (format name or Go layout)."},
	"unix_to_iso": {"(int) → string", "Unix seconds → RFC3339 UTC."},

	"regex_match":    {"(string, string) → bool", "Test regex match."},
	"regex_replace":  {"(string, string, string) → string", "Regex replace."},
	"regex_find_all": {"(string, string) → []string", "Find all regex matches."},

	"hostname":      {"() → string", "Host name (ambient, not gated)."},
	"dns_lookup":    {"(string) → []string", "Resolve host → IPs."},
	"port_check":    {"(string, string) → bool", "TCP connect test."},
	"wait_for_port": {"(string, string, string)", "Wait until host:port accepts connections."},
	"wait_for_url":  {"(string, string)", "Wait until URL returns success."},
	"public_ip":     {"() → string", "Fetch public IP via HTTP."},
	"local_ip":      {"() → string", "Primary local IP."},
	"interfaces":    {"() → string", "Network interface list."},
	"mac_address":   {"() → string", "MAC address."},
	"port_free":     {"(string) → bool", "Whether local port is free."},
	"find_free_port": {"() → int", "Find a free TCP port."},

	"get_os":   {"() → string", "Runtime GOOS (ambient)."},
	"get_arch": {"() → string", "Runtime GOARCH (ambient)."},
	"get_env":  {"(string) → string", "Read environment variable."},
	"set_env":  {"(string, string)", "Set environment variable."},
	"unset_env": {"(string)", "Unset environment variable."},
	"env_has":     {"(string) → bool", "Whether env var is set."},
	"env_default": {"(string, string) → string", "Env var or default."},
	"cwd":          {"() → string", "Current working directory."},
	"home_dir":     {"() → string", "User home directory path."},
	"temp_dir":     {"() → string", "OS temp directory path."},
	"cache_dir":    {"() → string", "User cache directory path."},
	"config_dir":   {"() → string", "User config directory path."},
	"data_dir":     {"() → string", "User data directory path."},
	"app_data_dir": {"() → string", "Platform app-data directory."},
	"exe_path":     {"() → string", "Running perch binary path."},
	"exe_dir":      {"() → string", "Directory of perch binary."},
	"script_path":  {"() → string", "Loaded .perch file path."},
	"script_dir":   {"() → string", "Directory of loaded .perch file."},
	"pid":          {"() → int", "Current process ID."},
	"user":         {"() → string", "Current username."},
	"cpu_count":    {"() → int", "Number of logical CPUs."},
	"os_version":   {"() → string", "OS version string (may spawn uname/etc.)."},

	"path_join": {"(...string) → string", "Join path elements."},
	"path_dir":  {"(string) → string", "Directory component."},
	"path_base": {"(string) → string", "Final path element."},
	"path_ext":  {"(string) → string", "File extension."},
	"path_abs":  {"(string) → string", "Absolute path."},
	"path_clean": {"(string) → string", "Clean path."},
	"path_rel":  {"(string, string) → string", "Relative path."},
	"expand_path": {"(string) → string", "Expand ~ and env in path string."},
	"is_abs":      {"(string) → bool", "Whether path is absolute."},

	"which":          {"(string) → string", "Resolve binary on PATH (ambient)."},
	"has_bin":        {"(string) → bool", "Whether binary exists on PATH."},
	"bin_version":    {"(string) → string", "Run binary --version and parse."},
	"pkg_install":    {"(string)", "Install package via detected package manager."},
	"pkg_installed":  {"(string) → bool", "Whether package is installed."},
	"pkg_uninstall":  {"(string)", "Uninstall package."},
	"detect_pkg_mgr": {"() → string", "Detected package manager name."},

	"timeout":  {"(number) … end", "Run body with wall-clock timeout."},
	"retry":    {"(number) … end", "Retry body on failure."},
	"parallel": {"… end", "Run body branches concurrently."},
	"with_env": {"(string, string) … end", "Temporary env binding for body."},
	"with_cwd": {"(string) … end", "Temporary cwd for body."},
	"sandbox":  {"… end", "Restrict capabilities for body."},

	"cache": {"(string, string, string) → string", "Persistent key-value cache op."},

	"bundle_hash":    {"(string) → string", "Hash of bundled file entry."},
	"bundle_dir":     {"() → string", "Extracted bundle directory."},
	"bundle_extract": {"(string)", "Extract bundle entry to DST."},

	"wasm_run": {"block", "Run WASM module declared in bundle."},

	"assert_eq": {"(any, any)", "Fail test if values differ."},
	"assert_neq": {"(any, any)", "Fail test if values equal."},
	"assert_contains": {"(string, string)", "Fail if haystack lacks needle."},
	"assert_not_contains": {"(string, string)", "Fail if haystack contains needle."},
	"assert_exists": {"(string)", "Fail if path missing."},
	"assert_not_exists": {"(string)", "Fail if path exists."},
	"assert_match": {"(string, string)", "Fail if string doesn't match regex."},

	"version_extract": {"(string) → string", "Extract semver from string."},
	"version_eq":      {"(string, string) → bool", "Version equality."},
	"version_ne":      {"(string, string) → bool", "Version inequality."},
	"version_gt":      {"(string, string) → bool", "Version greater-than."},
	"version_ge":      {"(string, string) → bool", "Version greater-or-equal."},
	"version_lt":      {"(string, string) → bool", "Version less-than."},
	"version_le":      {"(string, string) → bool", "Version less-or-equal."},
	"version_compat":  {"(string, string) → bool", "Semver compatibility check."},
	"assert_version_ge": {"(string, string)", "Fail test if version too old."},
	"assert_version":    {"(string, string, string)", "Fail test on version compare."},

	"process_running": {"(string) → bool", "Whether process name is running."},
	"kill_by_name":    {"(string)", "Kill processes by name (spawns pkill)."},
}
