[package]
name = "perch"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "perch"
path = "src/main.rs"

[dependencies]
perch-domain = { path = "../domain" }
perch-interpreter = { path = "../infra/interpreter" }
perch-capyloader = { path = "../infra/capyloader" }
perch-ops = { path = "../infra/ops" }
perch-audit = { path = "../infra/audit" }
perch-report = { path = "../infra/report" }
perch-preview = { path = "../infra/preview" }
perch-embed = { path = "../infra/embed" }
perch-httpserver = { path = "../infra/httpserver" }
perch-cli = { path = "../io/cli" }
perch-commandhelp = { path = "../usecases/commandhelp" }
perch-exportopscatalog = { path = "../usecases/exportopscatalog" }
perch-help = { path = "../usecases/help" }
perch-importsh = { path = "../usecases/importsh" }
perch-initconfig = { path = "../usecases/initconfig" }
perch-installlsp = { path = "../usecases/installlsp" }
perch-installvscode = { path = "../usecases/installvscode" }
perch-listcommands = { path = "../usecases/listcommands" }
perch-runbuild = { path = "../usecases/runbuild" }
perch-runcommand = { path = "../usecases/runcommand" }
perch-runserver = { path = "../usecases/runserver" }
perch-runshell = { path = "../usecases/runshell" }
perch-runtests = { path = "../usecases/runtests" }
perch-scan = { path = "../usecases/scan" }
perch-simulate = { path = "../usecases/simulate" }
perch-validate = { path = "../usecases/validate" }
