[package]
name = "perch-httpserver"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
perch-domain = { path = "../../domain" }
perch-interpreter = { path = "../interpreter" }
perch-ops = { path = "../ops" }
perch-scan = { path = "../../usecases/scan" }
perch-simulate = { path = "../../usecases/simulate" }
perch-validate = { path = "../../usecases/validate" }
serde.workspace = true
serde_json.workspace = true
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }

[dev-dependencies]
perch-capyloader = { path = "../capyloader" }
