// Generated from argdesc.go.
pub(crate) static COMMON_ARG_DESC: &[(&str, &str)] = &[
    (r##"path"##, r##"Filesystem path."##),
    (r##"src"##, r##"Source path."##),
    (r##"dst"##, r##"Destination path."##),
    (r##"link"##, r##"Symlink path to create."##),
    (r##"msg"##, r##"Message string."##),
    (r##"cmd"##, r##"Shell command string (first token is the binary name)."##),
    (r##"bin"##, r##"Binary name to execute (must be declared in `requires`)."##),
    (r##"argv"##, r##"Remaining argv tokens (space-separated in source; split at load time)."##),
    (r##"url"##, r##"HTTP(S) URL."##),
    (r##"name"##, r##"Name identifier."##),
    (r##"target"##, r##"Command name to invoke."##),
    (r##"code"##, r##"Exit code."##),
    (r##"host"##, r##"Hostname."##),
    (r##"content"##, r##"File contents to write."##),
    (r##"pattern"##, r##"Glob or regex pattern."##),
    (r##"key"##, r##"Lookup key."##),
    (r##"value"##, r##"Value."##),
    (r##"secs"##, r##"Duration in seconds."##),
    (r##"text"##, r##"Input text."##),
    (r##"pat"##, r##"Pattern string."##),
    (r##"n"##, r##"Count or index."##),
    (r##"fmt"##, r##"Format string."##),
    (r##"sep"##, r##"Separator string."##),
    (r##"old"##, r##"Substring or pattern to replace."##),
    (r##"new"##, r##"Replacement string."##),
    (r##"mode"##, r##"File mode (octal string, e.g. "0755")."##),
    (r##"hash"##, r##"Expected hash (algo:hex)."##),
];
pub(crate) static PER_OP_ARG_DESC: &[(&str, &str)] = &[
    (r##"exec.bin"##, r##"Binary to run directly (no shell); must be declared in `requires bin "…"`."##),
    (r##"shell.cmd"##, r##"Full shell command; first token must be a declared `bin`."##),
    (r##"download.url"##, r##"URL to fetch (host must be declared in `requires`)."##),
    (r##"download.dst"##, r##"Local path to write (must fall inside a declared `write` root)."##),
    (r##"get_env._0"##, r##"Environment variable name (must be declared in `requires env "…"`)."##),
    (r##"set_env._0"##, r##"Environment variable name to set."##),
    (r##"http_get._0"##, r##"URL to GET (hostname must be declared in `requires host "…"`)."##),
    (r##"replace._1"##, r##"Replacement spec as "OLD,NEW"."##),
    (r##"version_compat._0"##, r##"Required version constraint string."##),
];
