// Generated from docs.go opDocs.
pub(crate) static OP_DOCS: &[(&str, &str, &str)] = &[
    (r##"print"##, r##"(string)"##, r##"Print MSG + newline to stdout."##),
    (r##"println"##, r##"(string)"##, r##"Alias for print."##),
    (r##"eprintln"##, r##"(string)"##, r##"Print MSG + newline to stderr."##),
    (r##"shell"##, r##"(string)"##, r##"Run CMD via bash (POSIX) or cmd.exe (Windows). Deprecated — prefer exec."##),
    (r##"shell_output"##, r##"(string) → string"##, r##"Run CMD; capture stdout as the return value."##),
    (r##"shell_detached"##, r##"(string)"##, r##"Start CMD detached; return immediately."##),
    (r##"shell_in"##, r##"(string, string)"##, r##"Run CMD with stdin data."##),
    (r##"try_shell"##, r##"(string)"##, r##"Run CMD; on failure bind err and continue (used inside try/rescue)."##),
    (r##"exec"##, r##"(word, word…)"##, r##"Run BIN directly (no shell). Each token is one argv slot. Requires declared bin."##),
    (r##"exec_chain"##, r##"(exec clauses…)"##, r##"Chain exec clauses with && / || / ; short-circuit semantics."##),
    (r##"pipe"##, r##"block → string"##, r##"Wire stdout→stdin between exec stages in-process."##),
    (r##"fail"##, r##"(string)"##, r##"Exit the command with the given message."##),
    (r##"exit"##, r##"(int)"##, r##"Exit the process with the given code."##),
    (r##"sleep"##, r##"(number)"##, r##"Sleep for N seconds."##),
    (r##"run"##, r##"(ident)"##, r##"Call another command in the same program."##),
    (r##"list_commands"##, r##"()"##, r##"Print the visible command list."##),
    (r##"mkdir"##, r##"(string)"##, r##"Create directories (with parents)."##),
    (r##"cp"##, r##"(string, string)"##, r##"Copy src → dst."##),
    (r##"mv"##, r##"(string, string)"##, r##"Rename or move src → dst."##),
    (r##"rm"##, r##"(string)"##, r##"Remove path (recursive)."##),
    (r##"cd"##, r##"(string)"##, r##"Change interpreter cwd for subsequent ops."##),
    (r##"chmod"##, r##"(string, string)"##, r##"chmod path MODE (octal)."##),
    (r##"touch"##, r##"(string)"##, r##"Create or update file timestamp."##),
    (r##"write_file"##, r##"(string, string)"##, r##"Write CONTENT to PATH."##),
    (r##"read_file"##, r##"(string) → string"##, r##"Read PATH and return contents."##),
    (r##"exists"##, r##"(string) → bool"##, r##"Return whether PATH exists."##),
    (r##"is_dir"##, r##"(string) → bool"##, r##"Return whether PATH is a directory."##),
    (r##"is_file"##, r##"(string) → bool"##, r##"Return whether PATH is a regular file."##),
    (r##"file_size"##, r##"(string) → int"##, r##"Return size in bytes."##),
    (r##"list_dir"##, r##"(string) → string"##, r##"List directory entries."##),
    (r##"glob"##, r##"(string) → string"##, r##"Glob pattern match."##),
    (r##"append_file"##, r##"(string, string)"##, r##"Append CONTENT to PATH."##),
    (r##"append_line"##, r##"(string, string)"##, r##"Append one line to PATH."##),
    (r##"ensure_dir"##, r##"(string)"##, r##"mkdir -p equivalent."##),
    (r##"make_executable"##, r##"(string)"##, r##"chmod +x on PATH."##),
    (r##"ensure_line_in_file"##, r##"(string, string)"##, r##"Ensure LINE exists in PATH."##),
    (r##"replace_in_file"##, r##"(string, string, string)"##, r##"Replace OLD with NEW in PATH."##),
    (r##"backup_file"##, r##"(string)"##, r##"Copy PATH to PATH.bak."##),
    (r##"copy_dir"##, r##"(string, string)"##, r##"Recursively copy directory."##),
    (r##"symlink"##, r##"(string, string)"##, r##"Create symlink."##),
    (r##"read_link"##, r##"(string) → string"##, r##"Read symlink target."##),
    (r##"mktemp_dir"##, r##"() → string"##, r##"Create a temporary directory."##),
    (r##"mktemp_file"##, r##"() → string"##, r##"Create a temporary file."##),
    (r##"if"##, r##"EXPR … end"##, r##"Conditional block on comparison or truthiness."##),
    (r##"if_call"##, r##"FUNC ARG … end"##, r##"Conditional when FUNC(ARG) is truthy."##),
    (r##"for_each"##, r##"(list, ident) … end"##, r##"Iterate binding over list items."##),
    (r##"try"##, r##"block"##, r##"Try/rescue/finally error handling block."##),
    (r##"match"##, r##"EXPR … end"##, r##"Pattern dispatch block."##),
    (r##"os"##, r##"(string) … end"##, r##"Run body when host OS matches."##),
    (r##"arch"##, r##"(string) … end"##, r##"Run body when host arch matches."##),
    (r##"upper"##, r##"(string) → string"##, r##"Uppercase a string."##),
    (r##"lower"##, r##"(string) → string"##, r##"Lowercase a string."##),
    (r##"trim"##, r##"(string) → string"##, r##"Strip surrounding whitespace."##),
    (r##"capitalize"##, r##"(string) → string"##, r##"Title-case first letter."##),
    (r##"length"##, r##"(string) → int"##, r##"Byte length of string."##),
    (r##"contains"##, r##"(string, string) → bool"##, r##"Substring test."##),
    (r##"has_prefix"##, r##"(string, string) → bool"##, r##"Prefix test."##),
    (r##"has_suffix"##, r##"(string, string) → bool"##, r##"Suffix test."##),
    (r##"replace"##, r##"(string, string) → string"##, r##"Replace; second arg is "OLD,NEW"."##),
    (r##"split"##, r##"(string, string) → []string"##, r##"Split by separator."##),
    (r##"join"##, r##"([]any, string) → string"##, r##"Join with separator."##),
    (r##"repeat"##, r##"(string, int) → string"##, r##"Repeat N times."##),
    (r##"format"##, r##"(string, any) → string"##, r##"fmt.Sprintf-style format."##),
    (r##"grep"##, r##"(string, string) → string"##, r##"Keep lines matching regex PAT."##),
    (r##"reject"##, r##"(string, string) → string"##, r##"Keep lines NOT matching PAT."##),
    (r##"cut"##, r##"(int, string) → string"##, r##"Nth whitespace field per line."##),
    (r##"head"##, r##"(int, string) → string"##, r##"First N lines."##),
    (r##"tail"##, r##"(int, string) → string"##, r##"Last N lines."##),
    (r##"sort_lines"##, r##"(string) → string"##, r##"Sort lines lexicographically."##),
    (r##"uniq_lines"##, r##"(string) → string"##, r##"Collapse adjacent duplicate lines."##),
    (r##"count_lines"##, r##"(string) → int"##, r##"Count lines."##),
    (r##"md5"##, r##"(string) → string"##, r##"MD5 hex digest of string."##),
    (r##"sha1"##, r##"(string) → string"##, r##"SHA1 hex digest."##),
    (r##"sha256"##, r##"(string) → string"##, r##"SHA256 hex digest."##),
    (r##"crc32"##, r##"(string) → string"##, r##"CRC32 IEEE hex digest."##),
    (r##"md5_file"##, r##"(string) → string"##, r##"MD5 of file at PATH."##),
    (r##"sha1_file"##, r##"(string) → string"##, r##"SHA1 of file at PATH."##),
    (r##"sha256_file"##, r##"(string) → string"##, r##"SHA256 of file at PATH."##),
    (r##"verify_sha256"##, r##"(string, string) → bool"##, r##"Compare file hash to expected."##),
    (r##"base64_encode"##, r##"(string) → string"##, r##"Base64-encode."##),
    (r##"base64_decode"##, r##"(string) → string"##, r##"Base64-decode."##),
    (r##"hex_encode"##, r##"(string) → string"##, r##"Hex-encode."##),
    (r##"hex_decode"##, r##"(string) → string"##, r##"Hex-decode."##),
    (r##"url_encode"##, r##"(string) → string"##, r##"URL-percent-encode."##),
    (r##"url_decode"##, r##"(string) → string"##, r##"URL-percent-decode."##),
    (r##"json_parse"##, r##"(string) → any"##, r##"Parse JSON."##),
    (r##"json_stringify"##, r##"(any) → string"##, r##"Marshal to JSON."##),
    (r##"json_get"##, r##"(any, string) → any"##, r##"Dotted-path lookup in JSON value."##),
    (r##"http_get"##, r##"(string) → string"##, r##"HTTP GET; return body."##),
    (r##"http_post"##, r##"(string, string) → string"##, r##"HTTP POST with body."##),
    (r##"http_put"##, r##"(string, string) → string"##, r##"HTTP PUT."##),
    (r##"http_delete"##, r##"(string) → string"##, r##"HTTP DELETE."##),
    (r##"http_status"##, r##"(string) → int"##, r##"HTTP status code only."##),
    (r##"download"##, r##"(string, string)"##, r##"GET URL, save to DST."##),
    (r##"gzip"##, r##"(string, string)"##, r##"gzip SRC → DST."##),
    (r##"ungzip"##, r##"(string, string)"##, r##"ungzip SRC → DST."##),
    (r##"tar_create"##, r##"(string, string)"##, r##"Gzipped tar SRC_DIR → DST."##),
    (r##"tar_extract"##, r##"(string, string)"##, r##"Extract archive → DST."##),
    (r##"zip_create"##, r##"(string, string)"##, r##"Zip SRC_DIR → DST."##),
    (r##"zip_extract"##, r##"(string, string)"##, r##"Extract zip → DST."##),
    (r##"now"##, r##"(string?) → string"##, r##"Current time (format name or Go layout)."##),
    (r##"unix_to_iso"##, r##"(int) → string"##, r##"Unix seconds → RFC3339 UTC."##),
    (r##"regex_match"##, r##"(string, string) → bool"##, r##"Test regex match."##),
    (r##"regex_replace"##, r##"(string, string, string) → string"##, r##"Regex replace."##),
    (r##"regex_find_all"##, r##"(string, string) → []string"##, r##"Find all regex matches."##),
    (r##"hostname"##, r##"() → string"##, r##"Host name (ambient, not gated)."##),
    (r##"dns_lookup"##, r##"(string) → []string"##, r##"Resolve host → IPs."##),
    (r##"port_check"##, r##"(string, string) → bool"##, r##"TCP connect test."##),
    (r##"wait_for_port"##, r##"(string, string, string)"##, r##"Wait until host:port accepts connections."##),
    (r##"wait_for_url"##, r##"(string, string)"##, r##"Wait until URL returns success."##),
    (r##"public_ip"##, r##"() → string"##, r##"Fetch public IP via HTTP."##),
    (r##"local_ip"##, r##"() → string"##, r##"Primary local IP."##),
    (r##"interfaces"##, r##"() → string"##, r##"Network interface list."##),
    (r##"mac_address"##, r##"() → string"##, r##"MAC address."##),
    (r##"port_free"##, r##"(string) → bool"##, r##"Whether local port is free."##),
    (r##"find_free_port"##, r##"() → int"##, r##"Find a free TCP port."##),
    (r##"get_os"##, r##"() → string"##, r##"Runtime GOOS (ambient)."##),
    (r##"get_arch"##, r##"() → string"##, r##"Runtime GOARCH (ambient)."##),
    (r##"get_env"##, r##"(string) → string"##, r##"Read environment variable."##),
    (r##"set_env"##, r##"(string, string)"##, r##"Set environment variable."##),
    (r##"unset_env"##, r##"(string)"##, r##"Unset environment variable."##),
    (r##"env_has"##, r##"(string) → bool"##, r##"Whether env var is set."##),
    (r##"env_default"##, r##"(string, string) → string"##, r##"Env var or default."##),
    (r##"cwd"##, r##"() → string"##, r##"Current working directory."##),
    (r##"home_dir"##, r##"() → string"##, r##"User home directory path."##),
    (r##"temp_dir"##, r##"() → string"##, r##"OS temp directory path."##),
    (r##"cache_dir"##, r##"() → string"##, r##"User cache directory path."##),
    (r##"config_dir"##, r##"() → string"##, r##"User config directory path."##),
    (r##"data_dir"##, r##"() → string"##, r##"User data directory path."##),
    (r##"app_data_dir"##, r##"() → string"##, r##"Platform app-data directory."##),
    (r##"exe_path"##, r##"() → string"##, r##"Running perch binary path."##),
    (r##"exe_dir"##, r##"() → string"##, r##"Directory of perch binary."##),
    (r##"script_path"##, r##"() → string"##, r##"Loaded .perch file path."##),
    (r##"script_dir"##, r##"() → string"##, r##"Directory of loaded .perch file."##),
    (r##"pid"##, r##"() → int"##, r##"Current process ID."##),
    (r##"user"##, r##"() → string"##, r##"Current username."##),
    (r##"cpu_count"##, r##"() → int"##, r##"Number of logical CPUs."##),
    (r##"os_version"##, r##"() → string"##, r##"OS version string (may spawn uname/etc.)."##),
    (r##"path_join"##, r##"(...string) → string"##, r##"Join path elements."##),
    (r##"path_dir"##, r##"(string) → string"##, r##"Directory component."##),
    (r##"path_base"##, r##"(string) → string"##, r##"Final path element."##),
    (r##"path_ext"##, r##"(string) → string"##, r##"File extension."##),
    (r##"path_abs"##, r##"(string) → string"##, r##"Absolute path."##),
    (r##"path_clean"##, r##"(string) → string"##, r##"Clean path."##),
    (r##"path_rel"##, r##"(string, string) → string"##, r##"Relative path."##),
    (r##"expand_path"##, r##"(string) → string"##, r##"Expand ~ and env in path string."##),
    (r##"is_abs"##, r##"(string) → bool"##, r##"Whether path is absolute."##),
    (r##"which"##, r##"(string) → string"##, r##"Resolve binary on PATH (ambient)."##),
    (r##"has_bin"##, r##"(string) → bool"##, r##"Whether binary exists on PATH."##),
    (r##"bin_version"##, r##"(string) → string"##, r##"Run binary --version and parse."##),
    (r##"pkg_install"##, r##"(string)"##, r##"Install package via detected package manager."##),
    (r##"pkg_installed"##, r##"(string) → bool"##, r##"Whether package is installed."##),
    (r##"pkg_uninstall"##, r##"(string)"##, r##"Uninstall package."##),
    (r##"detect_pkg_mgr"##, r##"() → string"##, r##"Detected package manager name."##),
    (r##"timeout"##, r##"(number) … end"##, r##"Run body with wall-clock timeout."##),
    (r##"retry"##, r##"(number) … end"##, r##"Retry body on failure."##),
    (r##"parallel"##, r##"… end"##, r##"Run body branches concurrently."##),
    (r##"with_env"##, r##"(string, string) … end"##, r##"Temporary env binding for body."##),
    (r##"with_cwd"##, r##"(string) … end"##, r##"Temporary cwd for body."##),
    (r##"sandbox"##, r##"… end"##, r##"Restrict capabilities for body."##),
    (r##"cache"##, r##"(string, string, string) → string"##, r##"Persistent key-value cache op."##),
    (r##"bundle_hash"##, r##"(string) → string"##, r##"Hash of bundled file entry."##),
    (r##"bundle_dir"##, r##"() → string"##, r##"Extracted bundle directory."##),
    (r##"bundle_extract"##, r##"(string)"##, r##"Extract bundle entry to DST."##),
    (r##"wasm_run"##, r##"block"##, r##"Run WASM module declared in bundle."##),
    (r##"assert_eq"##, r##"(any, any)"##, r##"Fail test if values differ."##),
    (r##"assert_neq"##, r##"(any, any)"##, r##"Fail test if values equal."##),
    (r##"assert_contains"##, r##"(string, string)"##, r##"Fail if haystack lacks needle."##),
    (r##"assert_not_contains"##, r##"(string, string)"##, r##"Fail if haystack contains needle."##),
    (r##"assert_exists"##, r##"(string)"##, r##"Fail if path missing."##),
    (r##"assert_not_exists"##, r##"(string)"##, r##"Fail if path exists."##),
    (r##"assert_match"##, r##"(string, string)"##, r##"Fail if string doesn't match regex."##),
    (r##"version_extract"##, r##"(string) → string"##, r##"Extract semver from string."##),
    (r##"version_eq"##, r##"(string, string) → bool"##, r##"Version equality."##),
    (r##"version_ne"##, r##"(string, string) → bool"##, r##"Version inequality."##),
    (r##"version_gt"##, r##"(string, string) → bool"##, r##"Version greater-than."##),
    (r##"version_ge"##, r##"(string, string) → bool"##, r##"Version greater-or-equal."##),
    (r##"version_lt"##, r##"(string, string) → bool"##, r##"Version less-than."##),
    (r##"version_le"##, r##"(string, string) → bool"##, r##"Version less-or-equal."##),
    (r##"version_compat"##, r##"(string, string) → bool"##, r##"Semver compatibility check."##),
    (r##"assert_version_ge"##, r##"(string, string)"##, r##"Fail test if version too old."##),
    (r##"assert_version"##, r##"(string, string, string)"##, r##"Fail test on version compare."##),
    (r##"process_running"##, r##"(string) → bool"##, r##"Whether process name is running."##),
    (r##"kill_by_name"##, r##"(string)"##, r##"Kill processes by name (spawns pkill)."##),
];
