// Generated from examples.go.
pub(crate) static OP_EXAMPLES: &[(&str, &str)] = &[
    (r##"if"##, r##"if count > 0
    print "has items"
end"##),
    (r##"if_call"##, r##"if exists "./bin/app"
    print "built"
end"##),
    (r##"for_each"##, r##"for_each lines line
    print "${line}"
end"##),
    (r##"try"##, r##"try
    exec risky_cmd
rescue
    print "failed: ${err.message}"
end"##),
    (r##"match"##, r##"match os
    "darwin"
        print "mac"
    "linux"
        print "linux"
end"##),
    (r##"os"##, r##"os "linux"
    print "on linux"
end"##),
    (r##"arch"##, r##"arch "arm64"
    print "apple silicon"
end"##),
    (r##"timeout"##, r##"timeout 30
    exec long_running
end"##),
    (r##"retry"##, r##"retry 3
    http_get "https://example.com/health"
end"##),
    (r##"parallel"##, r##"parallel max=2
    exec task_a
    exec task_b
end"##),
    (r##"with_env"##, r##"with_env DEBUG "1"
    exec mytool
end"##),
    (r##"with_cwd"##, r##"with_cwd "${script_dir}"
    exec git status
end"##),
    (r##"sandbox"##, r##"sandbox no_network
    read_file "./config.json"
end"##),
    (r##"pipe"##, r##"out = pipe
    exec grep ERROR
    exec wc -l
end"##),
    (r##"exec_chain"##, r##"exec_chain
    exec git add .
    && exec git commit -m "wip"
    || print "nothing to commit"
end"##),
    (r##"exec"##, r##"exec git status"##),
    (r##"shell"##, r##"shell "git status""##),
    (r##"shell_output"##, r##"out = shell_output "git rev-parse HEAD""##),
    (r##"shell_detached"##, r##"shell_detached "myserver start""##),
    (r##"shell_in"##, r##"shell_in "cat" "input data""##),
    (r##"try_shell"##, r##"try_shell "maybe_fails""##),
    (r##"run"##, r##"run deploy"##),
    (r##"list_commands"##, r##"list_commands"##),
    (r##"write_file"##, r##"write_file "./out.txt" "hello""##),
    (r##"read_file"##, r##"body = read_file "./config.json""##),
    (r##"http_get"##, r##"body = http_get "https://example.com/api""##),
    (r##"http_post"##, r##"resp = http_post "https://example.com/hook" "{\"ok\":true}""##),
    (r##"download"##, r##"download "https://example.com/pkg.tgz" "./pkg.tgz""##),
    (r##"replace"##, r##"out = replace "hello world" "world,universe""##),
    (r##"json_get"##, r##"name = json_get "${doc}" "user.name""##),
    (r##"get_env"##, r##"path = get_env "PATH""##),
    (r##"set_env"##, r##"set_env "MY_FLAG" "1""##),
    (r##"cache"##, r##"hit = cache "build" "v1" "compute_key""##),
    (r##"bundle_dir"##, r##"assets = bundle_dir"##),
    (r##"bundle_extract"##, r##"bundle_extract "./plugin.wasm""##),
    (r##"wasm_run"##, r##"wasm_run
    wasm_arg count 42
    wasm_mount_read "./schema.json"
end"##),
    (r##"assert_eq"##, r##"assert_eq "${got}" "expected""##),
    (r##"assert_contains"##, r##"assert_contains "${log}" "OK""##),
    (r##"assert_exists"##, r##"assert_exists "./bin/app""##),
    (r##"assert_match"##, r##"assert_match "${tag}" "^v[0-9]+""##),
    (r##"assert_version_ge"##, r##"assert_version_ge "1.2.0" "1.0.0""##),
    (r##"version_compat"##, r##"ok = version_compat "^1.2" "1.2.3""##),
    (r##"wait_for_port"##, r##"wait_for_port "localhost" "8080" "30""##),
    (r##"wait_for_url"##, r##"wait_for_url "https://example.com/health" "60""##),
    (r##"ensure_line_in_file"##, r##"ensure_line_in_file "./.gitignore" "node_modules/""##),
    (r##"replace_in_file"##, r##"replace_in_file "./config.ini" "debug=false" "debug=true""##),
    (r##"csv_parse"##, r##"rows = csv_parse "${csv_text}""##),
    (r##"csv_stringify"##, r##"csv = csv_stringify rows"##),
];
pub(crate) static PER_ARG_SAMPLES: &[(&str, &str)] = &[
    (r##"bin"##, r##"git"##),
    (r##"argv"##, r##"status"##),
    (r##"msg"##, r##""hello""##),
    (r##"cmd"##, r##""echo hi""##),
    (r##"path"##, r##""./data""##),
    (r##"src"##, r##""./src""##),
    (r##"dst"##, r##""./dst""##),
    (r##"content"##, r##""line one""##),
    (r##"url"##, r##""https://example.com""##),
    (r##"host"##, r##""localhost""##),
    (r##"target"##, r##"deploy"##),
    (r##"code"##, r##"1"##),
    (r##"pattern"##, r##""*.json""##),
    (r##"mode"##, r##""0755""##),
    (r##"hash"##, r##""sha256:abc123""##),
    (r##"key"##, r##""cache-key""##),
    (r##"value"##, r##""42""##),
    (r##"secs"##, r##"5"##),
    (r##"text"##, r##""input text""##),
    (r##"pat"##, r##""ERROR""##),
    (r##"n"##, r##"10"##),
    (r##"fmt"##, r##""%s v%d""##),
    (r##"sep"##, r##"",""##),
    (r##"old"##, r##""old""##),
    (r##"new"##, r##""new""##),
    (r##"link"##, r##""./link""##),
    (r##"name"##, r##"line"##),
    (r##"line"##, r##""setting=true""##),
    (r##"pkg"##, r##""curl""##),
    (r##"proc"##, r##""nginx""##),
    (r##"port"##, r##""8080""##),
    (r##"timeout"##, r##""30""##),
    (r##"layout"##, r##""rfc3339""##),
    (r##"constraint"##, r##""^1.0""##),
    (r##"version"##, r##""1.2.3""##),
    (r##"min"##, r##""1.0.0""##),
    (r##"entry"##, r##""plugin.wasm""##),
    (r##"module"##, r##""validator""##),
    (r##"func"##, r##""validate""##),
    (r##"scenario"##, r##""default""##),
    (r##"fixture"##, r##""./fixture.json""##),
    (r##"max"##, r##"3"##),
    (r##"env_name"##, r##""DEBUG""##),
    (r##"env_value"##, r##""1""##),
    (r##"dir"##, r##""${script_dir}""##),
    (r##"expr"##, r##""linux""##),
    (r##"list"##, r##"items"##),
    (r##"ident"##, r##"item"##),
    (r##"haystack"##, r##""hello world""##),
    (r##"needle"##, r##""world""##),
    (r##"left"##, r##""1.2.3""##),
    (r##"right"##, r##""1.0.0""##),
    (r##"a"##, r##""a""##),
    (r##"b"##, r##""b""##),
    (r##"got"##, r##""actual""##),
    (r##"want"##, r##""expected""##),
    (r##"file"##, r##""./file.txt""##),
    (r##"archive"##, r##""./dist.tar.gz""##),
    (r##"zip"##, r##""./dist.zip""##),
    (r##"data"##, r##""stdin data""##),
    (r##"stdin"##, r##""input""##),
    (r##"stage"##, r##""grep foo""##),
    (r##"clause"##, r##"exec echo ok"##),
    (r##"wasm_path"##, r##""./plugin.wasm""##),
    (r##"mount"##, r##""./data""##),
    (r##"allow"##, r##""api.example.com""##),
    (r##"label"##, r##""prod""##),
    (r##"kind"##, r##""ErrNotFound""##),
    (r##"field"##, r##""name""##),
    (r##"json"##, r##""{\"ok\":true}""##),
    (r##"csv"##, r##""a,b\n1,2""##),
    (r##"rows"##, r##"rows"##),
    (r##"doc"##, r##"doc"##),
    (r##"ip"##, r##""127.0.0.1""##),
    (r##"service"##, r##""http""##),
    (r##"signal"##, r##""SIGTERM""##),
    (r##"handler"##, r##"cleanup"##),
    (r##"root"##, r##""${script_dir}""##),
    (r##"glob"##, r##""**/*.json""##),
    (r##"line_no"##, r##"1"##),
    (r##"count"##, r##"3"##),
    (r##"delay"##, r##"1"##),
    (r##"attempts"##, r##"3"##),
    (r##"seconds"##, r##"5"##),
    (r##"ms"##, r##"500"##),
    (r##"tag"##, r##""v1.2.3""##),
    (r##"regex"##, r##""^[a-z]+$""##),
    (r##"repl"##, r##""X""##),
    (r##"subject"##, r##""abc123""##),
    (r##"timestamp"##, r##"1700000000"##),
    (r##"format"##, r##""rfc3339""##),
    (r##"algo"##, r##""sha256""##),
    (r##"expected"##, r##""deadbeef""##),
    (r##"actual"##, r##""deadbeef""##),
    (r##"bin_name"##, r##""go""##),
    (r##"flag"##, r##""--version""##),
    (r##"manager"##, r##""apt""##),
    (r##"package"##, r##""curl""##),
    (r##"command"##, r##""deploy""##),
    (r##"arg"##, r##""--verbose""##),
    (r##"cwd"##, r##""${script_dir}""##),
    (r##"pid"##, r##""1234""##),
    (r##"uid"##, r##""1000""##),
    (r##"user"##, r##""alice""##),
    (r##"hostname"##, r##""myhost""##),
    (r##"scheme"##, r##""https""##),
    (r##"method"##, r##""GET""##),
    (r##"body"##, r##""{}""##),
    (r##"headers"##, r##""Content-Type: application/json""##),
    (r##"token"##, r##""secret""##),
    (r##"namespace"##, r##""default""##),
    (r##"resource"##, r##""pod/app""##),
    (r##"policy"##, r##""strict""##),
    (r##"manifest"##, r##""./k8s.yaml""##),
    (r##"diff"##, r##""./changes.patch""##),
    (r##"summary"##, r##""risk: low""##),
    (r##"risk"##, r##""low""##),
    (r##"schema"##, r##""./schema.json""##),
    (r##"input"##, r##""./input.json""##),
    (r##"output"##, r##""./output.json""##),
    (r##"plugin"##, r##""discount""##),
    (r##"cart"##, r##""./cart.json""##),
    (r##"tax_rate"##, r##""0.08""##),
    (r##"amount"##, r##""100""##),
    (r##"currency"##, r##""USD""##),
    (r##"locale"##, r##""en_US""##),
    (r##"timezone"##, r##""UTC""##),
    (r##"date"##, r##""2024-01-01""##),
    (r##"time"##, r##""12:00:00""##),
    (r##"duration"##, r##""30s""##),
    (r##"interval"##, r##""1s""##),
    (r##"limit"##, r##"100"##),
    (r##"offset"##, r##"0"##),
    (r##"page"##, r##"1"##),
    (r##"size"##, r##"20"##),
    (r##"filter"##, r##""active""##),
    (r##"query"##, r##""status=ok""##),
    (r##"endpoint"##, r##""/health""##),
    (r##"base"##, r##"".""##),
    (r##"rel"##, r##""./sub""##),
    (r##"ext"##, r##"".txt""##),
    (r##"elements"##, r##""a" "b""##),
    (r##"parts"##, r##""a" "b""##),
    (r##"paths"##, r##""a" "b""##),
    (r##"values"##, r##""x" "y""##),
    (r##"items"##, r##"items"##),
    (r##"item"##, r##"item"##),
    (r##"who"##, r##""world""##),
    (r##"what"##, r##""build""##),
    (r##"where"##, r##""${temp_dir}""##),
    (r##"when"##, r##""now""##),
    (r##"why"##, r##""deploy""##),
    (r##"how"##, r##""exec""##),
    (r##"status"##, r##""ok""##),
    (r##"state"##, r##""ready""##),
    (r##"level"##, r##""info""##),
    (r##"message"##, r##""done""##),
    (r##"error"##, r##""failed""##),
    (r##"reason"##, r##""timeout""##),
    (r##"detail"##, r##""connection refused""##),
    (r##"source"##, r##""./src""##),
    (r##"dest"##, r##""./dest""##),
    (r##"from"##, r##""./from""##),
    (r##"to"##, r##""./to""##),
];
