[package]
name = "perch-lsp"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "perch-lsp"
path = "src/main.rs"

[dependencies]
perch-domain = { path = "../../domain" }
perch-capyloader = { path = "../../infra/capyloader" }
perch-ops = { path = "../../infra/ops" }
perch-validate = { path = "../../usecases/validate" }
regex = "1"
serde.workspace = true
serde_json.workspace = true
